book:
  google-analytics: "G-EK42ND3YYR"
  cookie-consent: true
  chapters:
    - index.qmd
    - 01-Introduction.ipynb
    - 02-Descriptive-Statistics.ipynb
    # - 03-Probability.ipynb
    # - 04-Combinatorics.ipynb 
#    - 02-Garden-of-Forking-Data.qmd
    - references.qmd  