project:
  type: book
  
book:
  title: "Basic Statistics"
  author: "Boyko Amarov"
  date: "10/01/2024"
  chapters:
    - index.qmd
    - 01-Introduction.ipynb
    - 02-Garden-of-Forking-Data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex

editor: visual
