# Setup {.unnumbered}

```{python}
#| echo: false

import yaml
from utils.qr import create_qr_code
from IPython.display import Markdown

# Load the YAML file
with open('settings.yml', 'r') as file:
    cs = yaml.safe_load(file)
```

:::{.callout-note}
## Website URL

[`{python} cs['url']`](`{python} cs['url']`){style="font-size:2em; margin-left: 1em;"}

```{python}
#| echo: false
display(create_qr_code(cs['url']))
```
:::

## Schedule

1.  Wed 9:30-11:00 in room 520
2.  Wed 12:15-14:00 in room 215k

## Grading

TBA

## GitHub Repository

All course materials for the exercise classes will be available in the GitHub repository:

[`{python} cs['github']`](`{python} cs['github']`)

## GitHub Account

Open a GitHub account at <https://github.com/signup>. While you don't need an account to download the course materials, you will need one to receive and submit assignments (this will be explained in details during the exercise classes). You can also apply for the GitHub student benefits at <https://education.github.com/benefits>. If approved you can receive free access to the GitHub Pro plan and to GitHub Copilot, an AI tool that helps you write code.


## Google Account

We will be using Python through Jupyter notebooks in the exercise classes. The recommended way to work on the exercises is to use Google Colab, a cloud service that allows you to run Python code in the browser (and includes a generous free tier). You will need a Google account to use Google Colab. If you don't have one, you can create one at <https://accounts.google.com/signup>.

## Local Software Setup (Optional)

The recommended way to run the notebooks is Google Colab. However, if you prefer to work locally, you will need to install a recent version of Python (3.7 or later) and the dependencies listed in the `environment.yml` file in the GitHub repository.

:::{.callout-note collapsed="true"}
## Windows: Using Installers

1. Install Git for you operating system from [https://git-scm.com/downloads/](https://git-scm.com/downloads).

3. Install Visual Studio Code (VSC) from [https://code.visualstudio.com/](https://code.visualstudio.com/)

4. Install `miniconda` from [https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html)

:::


:::{.callout-note collapsed=true}
## Windows: Using Chocolatey

1. Click on the Windows start button and type `cmd`. Right-click on the `Command Prompt` and select `Run as administrator`.
2. Copy and paste the following command and press enter:

    ```{cmd}
    @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
    ```
3. Close the `Command Prompt` and open it again as administrator.
4. Copy and paste the following command and press enter:

    ```{cmd}
    choco install git vscode miniconda3
    refreshenv
    ```
:::

Open the command promt (cmd) and type

```{cmd}
%USERPROFILE%\miniconda3\Scripts\conda.exe env create -f environment.yml
```

