url: https://febse.github.io/stat2024/
title: Basic Statistics
author: Boyko Amarov
github: https://github.com/febse/stat2024/
githubHttps: https://github.com/febse/stat2024.git
githubCli: gh repo clone febse/stat2024
